theme: jekyll-theme-cayman
Title: The Effect of Poor Source Code Lexicon and Readability on Developers Cognitive Load
description: This is the online replication package for ICPC 2018 Technical Research submission. 