theme: jekyll-theme-cayman
Title: The Effect of Poor Source Code Lexicon and Readability on Developers Cognitive Load
description: This is the online replication package for ICPC 2018 Technical Research submission. This package includes the code snippets used for control group and three treatment groups (LA, Structural, LA & Structural).
